services:
  db:
    container_name: postgres-spring-boot
    image: postgres:latest
    environment:
      POSTGRES_USER: sasamoahkb
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springboot
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:


    